/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type TarasShape = {
  _type: 'tarasShape';
  shapeNumber: '1' | '2' | '3' | '4';
  label: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  sides: Array<string>;
};

export type ProcessStep = {
  _type: 'processStep';
  number: string;
  icon:
    | 'mail'
    | 'calculator'
    | 'ruler'
    | 'file-check'
    | 'file-signature'
    | 'hammer'
    | 'shield-check';
  title: string;
  description?: string;
};

export type AboutBadge = {
  _type: 'aboutBadge';
  icon: 'gem' | 'target' | 'wrench' | 'award';
  title: string;
  description: string;
};

export type OfferCard = {
  _type: 'offerCard';
  title: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  icon?:
    | 'layers'
    | 'sliders-horizontal'
    | 'sparkles'
    | 'sun'
    | 'wind'
    | 'shield'
    | 'house'
    | 'boxes';
  featured?: boolean;
  badges?: Array<string>;
  offerSlug?:
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe'
    | 'tarasy-kompozytowe'
    | 'tarasy-gresowe'
    | 'tarasy-drewniane'
    | 'elewacje-kompozytowe'
    | 'schody-modulowe';
};

export type TrustStat = {
  _type: 'trustStat';
  icon: 'shield' | 'clock' | 'award' | 'users' | 'star' | 'check' | 'tool' | 'map';
  value?: string;
  label: string;
  description?: string;
};

export type HeroStat = {
  _type: 'heroStat';
  value: string;
  label: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  seoDescription?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroHeadline: string;
  heroSubheadline?: string;
  relatedFormSlug?: 'zadaszenie' | 'zaluzje' | 'taras' | 'schody';
  category:
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe'
    | 'tarasy-kompozytowe'
    | 'tarasy-gresowe'
    | 'tarasy-drewniane'
    | 'elewacje-kompozytowe'
    | 'schody-modulowe';
  benefitsEyebrow?: string;
  benefitsHeadline?: string;
  benefitsDescription?: string;
  benefits?: Array<{
    icon:
      | 'shield'
      | 'clock'
      | 'award'
      | 'users'
      | 'star'
      | 'check'
      | 'tool'
      | 'map'
      | 'sun'
      | 'droplets'
      | 'ruler'
      | 'zap';
    title: string;
    description?: string;
    _type: 'benefit';
    _key: string;
  }>;
  brandsEyebrow?: string;
  brandsHeadline?: string;
  brandsDescription?: string;
  brands?: Array<{
    name: string;
    shortDescription?: string;
    fullDescription?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    specs?: Array<string>;
    _type: 'brand';
    _key: string;
  }>;
  techSpecsHeadline?: string;
  techSpecsDescription?: string;
  techSpecs?: Array<{
    icon:
      | 'shield'
      | 'clock'
      | 'award'
      | 'users'
      | 'star'
      | 'check'
      | 'tool'
      | 'map'
      | 'sun'
      | 'droplets'
      | 'ruler'
      | 'zap'
      | 'home'
      | 'euro'
      | 'file'
      | 'phone';
    title: string;
    content: string;
    _type: 'techSpec';
    _key: string;
  }>;
  formCtaHeadline?: string;
  formCtaSubheadline?: string;
  formCtaButtonLabel?: string;
  formCtaBullets?: Array<string>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  city: string;
  category:
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe'
    | 'tarasy-kompozytowe'
    | 'tarasy-gresowe'
    | 'tarasy-drewniane'
    | 'elewacje-kompozytowe'
    | 'schody-modulowe';
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  surface?: number;
  isFeatured?: boolean;
};

export type SchodyFormConfig = {
  _id: string;
  _type: 'schodyFormConfig';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  diagram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
};

export type TarasFormConfig = {
  _id: string;
  _type: 'tarasFormConfig';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  shapes: Array<
    {
      _key: string;
    } & TarasShape
  >;
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    logoImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    text?: string;
    iconLetter?: string;
    href?: string;
  };
  tagline?: string;
  socialLinks?: Array<{
    platform: 'instagram' | 'facebook' | 'linkedin' | 'youtube' | 'x' | 'tiktok';
    href: string;
    _key: string;
  }>;
  contactName?: string;
  contactAddress?: string;
  contactPhone?: string;
  contactEmail?: string;
  copyrightText?: string;
};

export type ProcessTimeline = {
  _id: string;
  _type: 'processTimeline';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
  steps: Array<
    {
      _key: string;
    } & ProcessStep
  >;
};

export type BottomCtaSection = {
  _id: string;
  _type: 'bottomCtaSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  eyebrow?: string;
  headline: string;
  headlineAccent?: string;
  subheadline?: string;
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  bullets?: Array<string>;
  contactEyebrow?: string;
  contactNote?: string;
  contactPhone?: string;
  contactEmail?: string;
  showroomLabel?: string;
  showroomDescription?: string;
  showroomAddress?: string;
  officeLabel?: string;
  officeDescription?: string;
};

export type RealizacjePage = {
  _id: string;
  _type: 'realizacjePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
};

export type FeaturedProjectsSection = {
  _id: string;
  _type: 'featuredProjectsSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
};

export type AboutSection = {
  _id: string;
  _type: 'aboutSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cardImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  cardContent?: {
    title: string;
    description: string;
  };
  eyebrow?: string;
  headline: string;
  description?: string;
  badges?: Array<
    {
      _key: string;
    } & AboutBadge
  >;
};

export type OfferSection = {
  _id: string;
  _type: 'offerSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
  ctaLabel: string;
  ctaHref: string;
  cards?: Array<
    {
      _key: string;
    } & OfferCard
  >;
};

export type TrustSection = {
  _id: string;
  _type: 'trustSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
  stats?: Array<
    {
      _key: string;
    } & TrustStat
  >;
  badges?: Array<string>;
};

export type HeroSection = {
  _id: string;
  _type: 'heroSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  headline: string;
  headlineAccent?: string;
  subheadline?: string;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  stats?: Array<
    {
      _key: string;
    } & HeroStat
  >;
};

export type Navbar = {
  _id: string;
  _type: 'navbar';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    logoImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    text?: string;
    iconLetter?: string;
    href?: string;
  };
  ctaButton?: {
    label?: string;
    href?: string;
  };
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: 'image';
  };
};

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask';
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status';
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations';
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type';
  type?: string;
};

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field';
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context';
};

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context';
  reference: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: 'assist.instruction.context';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput';
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: 'normal';
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef';
  path?: string;
};

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction';
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field';
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | TarasShape
  | ProcessStep
  | AboutBadge
  | OfferCard
  | TrustStat
  | HeroStat
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Project
  | SchodyFormConfig
  | TarasFormConfig
  | Footer
  | ProcessTimeline
  | BottomCtaSection
  | RealizacjePage
  | FeaturedProjectsSection
  | AboutSection
  | OfferSection
  | TrustSection
  | HeroSection
  | Navbar
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: 'image';
  };
} | null;

// Source: sanity/lib/queries.ts
// Variable: navbarQuery
// Query: *[_type == "navbar"][0]
export type NavbarQueryResult = {
  _id: string;
  _type: 'navbar';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    logoImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    text?: string;
    iconLetter?: string;
    href?: string;
  };
  ctaButton?: {
    label?: string;
    href?: string;
  };
} | null;

// Source: sanity/lib/queries.ts
// Variable: heroQuery
// Query: *[_type == "heroSection"][0]
export type HeroQueryResult = {
  _id: string;
  _type: 'heroSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  headline: string;
  headlineAccent?: string;
  subheadline?: string;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  stats?: Array<
    {
      _key: string;
    } & HeroStat
  >;
} | null;

// Source: sanity/lib/queries.ts
// Variable: trustQuery
// Query: *[_type == "trustSection"][0]
export type TrustQueryResult = {
  _id: string;
  _type: 'trustSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
  stats?: Array<
    {
      _key: string;
    } & TrustStat
  >;
  badges?: Array<string>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: offerQuery
// Query: *[_type == "offerSection"][0]
export type OfferQueryResult = {
  _id: string;
  _type: 'offerSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
  ctaLabel: string;
  ctaHref: string;
  cards?: Array<
    {
      _key: string;
    } & OfferCard
  >;
} | null;

// Source: sanity/lib/queries.ts
// Variable: aboutQuery
// Query: *[_type == "aboutSection"][0]
export type AboutQueryResult = {
  _id: string;
  _type: 'aboutSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cardImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  cardContent?: {
    title: string;
    description: string;
  };
  eyebrow?: string;
  headline: string;
  description?: string;
  badges?: Array<
    {
      _key: string;
    } & AboutBadge
  >;
} | null;

// Source: sanity/lib/queries.ts
// Variable: featuredProjectsSectionQuery
// Query: *[_type == "featuredProjectsSection"][0]
export type FeaturedProjectsSectionQueryResult = {
  _id: string;
  _type: 'featuredProjectsSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: realizacjePageQuery
// Query: *[_type == "realizacjePage"][0]
export type RealizacjePageQueryResult = {
  _id: string;
  _type: 'realizacjePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: bottomCtaQuery
// Query: *[_type == "bottomCtaSection"][0]
export type BottomCtaQueryResult = {
  _id: string;
  _type: 'bottomCtaSection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  eyebrow?: string;
  headline: string;
  headlineAccent?: string;
  subheadline?: string;
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  bullets?: Array<string>;
  contactEyebrow?: string;
  contactNote?: string;
  contactPhone?: string;
  contactEmail?: string;
  showroomLabel?: string;
  showroomDescription?: string;
  showroomAddress?: string;
  officeLabel?: string;
  officeDescription?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: processTimelineQuery
// Query: *[_type == "processTimeline"][0]
export type ProcessTimelineQueryResult = {
  _id: string;
  _type: 'processTimeline';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline: string;
  subheadline?: string;
  steps: Array<
    {
      _key: string;
    } & ProcessStep
  >;
} | null;

// Source: sanity/lib/queries.ts
// Variable: footerQuery
// Query: *[_type == "footer"][0]
export type FooterQueryResult = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    logoImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    text?: string;
    iconLetter?: string;
    href?: string;
  };
  tagline?: string;
  socialLinks?: Array<{
    platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok' | 'x' | 'youtube';
    href: string;
    _key: string;
  }>;
  contactName?: string;
  contactAddress?: string;
  contactPhone?: string;
  contactEmail?: string;
  copyrightText?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: tarasFormConfigQuery
// Query: *[_type == "tarasFormConfig"][0]{    shapes[]{      _key,      shapeNumber,      label,      image,      sides    }  }
export type TarasFormConfigQueryResult = {
  shapes: Array<{
    _key: string;
    shapeNumber: '1' | '2' | '3' | '4';
    label: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    } | null;
    sides: Array<string>;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: schodyFormConfigQuery
// Query: *[_type == "schodyFormConfig"][0]{    diagram  }
export type SchodyFormConfigQueryResult = {
  diagram: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: featuredProjectsQuery
// Query: *[_type == "project" && isFeatured == true] | order(_createdAt desc){    _id,    title,    city,    category,    coverImage  }
export type FeaturedProjectsQueryResult = Array<{
  _id: string;
  title: string;
  city: string;
  category:
    | 'elewacje-kompozytowe'
    | 'schody-modulowe'
    | 'tarasy-drewniane'
    | 'tarasy-gresowe'
    | 'tarasy-kompozytowe'
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe';
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(_createdAt desc){    _id,    title,    city,    category,    surface,    coverImage  }
export type AllProjectsQueryResult = Array<{
  _id: string;
  title: string;
  city: string;
  category:
    | 'elewacje-kompozytowe'
    | 'schody-modulowe'
    | 'tarasy-drewniane'
    | 'tarasy-gresowe'
    | 'tarasy-kompozytowe'
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe';
  surface: number | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: galleryProjectsByCategoryQuery
// Query: *[_type == "project" && category == $category] | order(_createdAt desc){    _id,    title,    city,    category,    coverImage  }
export type GalleryProjectsByCategoryQueryResult = Array<{
  _id: string;
  title: string;
  city: string;
  category:
    | 'elewacje-kompozytowe'
    | 'schody-modulowe'
    | 'tarasy-drewniane'
    | 'tarasy-gresowe'
    | 'tarasy-kompozytowe'
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe';
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: serviceSlugsQuery
// Query: *[_type == "service" && defined(slug.current)]{ "slug": slug.current }
export type ServiceSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: serviceBySlugQuery
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    seoDescription,    heroImage,    heroHeadline,    heroSubheadline,    relatedFormSlug,    category,    benefitsEyebrow,    benefitsHeadline,    benefitsDescription,    benefits[]{      _key,      icon,      title,      description    },    brandsEyebrow,    brandsHeadline,    brandsDescription,    brands[]{      _key,      name,      shortDescription,      fullDescription,      image,      specs    },    techSpecsHeadline,    techSpecsDescription,    techSpecs[]{      _key,      icon,      title,      content    },    formCtaHeadline,    formCtaSubheadline,    formCtaButtonLabel,    formCtaBullets  }
export type ServiceBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  seoDescription: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  heroHeadline: string;
  heroSubheadline: string | null;
  relatedFormSlug: 'schody' | 'taras' | 'zadaszenie' | 'zaluzje' | null;
  category:
    | 'elewacje-kompozytowe'
    | 'schody-modulowe'
    | 'tarasy-drewniane'
    | 'tarasy-gresowe'
    | 'tarasy-kompozytowe'
    | 'zadaszenia-tarasowe'
    | 'zaluzje-tarasowe';
  benefitsEyebrow: string | null;
  benefitsHeadline: string | null;
  benefitsDescription: string | null;
  benefits: Array<{
    _key: string;
    icon:
      | 'award'
      | 'check'
      | 'clock'
      | 'droplets'
      | 'map'
      | 'ruler'
      | 'shield'
      | 'star'
      | 'sun'
      | 'tool'
      | 'users'
      | 'zap';
    title: string;
    description: string | null;
  }> | null;
  brandsEyebrow: string | null;
  brandsHeadline: string | null;
  brandsDescription: string | null;
  brands: Array<{
    _key: string;
    name: string;
    shortDescription: string | null;
    fullDescription: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    } | null;
    specs: Array<string> | null;
  }> | null;
  techSpecsHeadline: string | null;
  techSpecsDescription: string | null;
  techSpecs: Array<{
    _key: string;
    icon:
      | 'award'
      | 'check'
      | 'clock'
      | 'droplets'
      | 'euro'
      | 'file'
      | 'home'
      | 'map'
      | 'phone'
      | 'ruler'
      | 'shield'
      | 'star'
      | 'sun'
      | 'tool'
      | 'users'
      | 'zap';
    title: string;
    content: string;
  }> | null;
  formCtaHeadline: string | null;
  formCtaSubheadline: string | null;
  formCtaButtonLabel: string | null;
  formCtaBullets: Array<string> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult;
    '*[_type == "navbar"][0]': NavbarQueryResult;
    '*[_type == "heroSection"][0]': HeroQueryResult;
    '*[_type == "trustSection"][0]': TrustQueryResult;
    '*[_type == "offerSection"][0]': OfferQueryResult;
    '*[_type == "aboutSection"][0]': AboutQueryResult;
    '*[_type == "featuredProjectsSection"][0]': FeaturedProjectsSectionQueryResult;
    '*[_type == "realizacjePage"][0]': RealizacjePageQueryResult;
    '*[_type == "bottomCtaSection"][0]': BottomCtaQueryResult;
    '*[_type == "processTimeline"][0]': ProcessTimelineQueryResult;
    '*[_type == "footer"][0]': FooterQueryResult;
    '*[_type == "tarasFormConfig"][0]{\n    shapes[]{\n      _key,\n      shapeNumber,\n      label,\n      image,\n      sides\n    }\n  }': TarasFormConfigQueryResult;
    '*[_type == "schodyFormConfig"][0]{\n    diagram\n  }': SchodyFormConfigQueryResult;
    '*[_type == "project" && isFeatured == true] | order(_createdAt desc){\n    _id,\n    title,\n    city,\n    category,\n    coverImage\n  }': FeaturedProjectsQueryResult;
    '*[_type == "project"] | order(_createdAt desc){\n    _id,\n    title,\n    city,\n    category,\n    surface,\n    coverImage\n  }': AllProjectsQueryResult;
    '*[_type == "project" && category == $category] | order(_createdAt desc){\n    _id,\n    title,\n    city,\n    category,\n    coverImage\n  }': GalleryProjectsByCategoryQueryResult;
    '*[_type == "service" && defined(slug.current)]{ "slug": slug.current }': ServiceSlugsQueryResult;
    '*[_type == "service" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    seoDescription,\n    heroImage,\n    heroHeadline,\n    heroSubheadline,\n    relatedFormSlug,\n    category,\n    benefitsEyebrow,\n    benefitsHeadline,\n    benefitsDescription,\n    benefits[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    brandsEyebrow,\n    brandsHeadline,\n    brandsDescription,\n    brands[]{\n      _key,\n      name,\n      shortDescription,\n      fullDescription,\n      image,\n      specs\n    },\n    techSpecsHeadline,\n    techSpecsDescription,\n    techSpecs[]{\n      _key,\n      icon,\n      title,\n      content\n    },\n    formCtaHeadline,\n    formCtaSubheadline,\n    formCtaButtonLabel,\n    formCtaBullets\n  }': ServiceBySlugQueryResult;
  }
}
